In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers
import matplotlib.pyplot as plt
%matplotlib inline

# Reading in the Data

In [2]:
rebound_data = pd.read_csv("~/Desktop/Deep_Learning/nba-movement-data/rebounding_data/data_sets/landing_isotropic_train_augmented.csv")

In [3]:
rebound_data.head(20)

Unnamed: 0 group   GAME_ID  GAME_EVENT_ID       play_id  play_num  \
0            1  test  21500001             84  215000010084         1   
1            2  test  21500001             84  215000010084         1   
2            3  test  21500001             84  215000010084         1   
3            4  test  21500001             84  215000010084         1   
4            5  test  21500001             84  215000010084         1   
5            6  test  21500001             84  215000010084         1   
6            7  test  21500001             84  215000010084         1   
7            8  test  21500001             84  215000010084         1   
8            9  test  21500001             84  215000010084         1   
9           10  test  21500001             84  215000010084         1   
10          11  test  21500001             84  215000010084         1   
11          12  test  21500001             84  215000010084         1   
12          13  test  21500001             84  215000010084         1   
13          14  test  21500001             84  215000010084         1   
14          15  test  21500001             84  215000010084         1   
15          16  test  21500001             84  215000010084         1   
16          17  test  21500001             84  215000010084         1   
17          18  test  21500001             84  215000010084         1   
18          19  test  21500001             84  215000010084         1   
19          20  test  21500001             84  215000010084         1   

    player_num1  player_num2  player_id1  player_id2  ...  basket_x_diff  \
0             1            1      202694      202694  ...        3.21419   
1             1            2      202694      202704  ...        3.21419   
2             1            3      202694      203083  ...        3.21419   
3             1            4      202694      203484  ...        3.21419   
4             1            5      202694     1626169  ...        3.21419   
5             1            6      202694      200794  ...        3.21419   
6             1            7      202694      201168  ...        3.21419   
7             1            8      202694      203471  ...        3.21419   
8             1            9      202694      203934  ...        3.21419   
9             1           10      202694      200757  ...        3.21419   
10            2            1      202704      202694  ...       13.33623   
11            2            2      202704      202704  ...       13.33623   
12            2            3      202704      203083  ...       13.33623   
13            2            4      202704      203484  ...       13.33623   
14            2            5      202704     1626169  ...       13.33623   
15            2            6      202704      200794  ...       13.33623   
16            2            7      202704      201168  ...       13.33623   
17            2            8      202704      203471  ...       13.33623   
18            2            9      202704      203934  ...       13.33623   
19            2           10      202704      200757  ...       13.33623   

    basket_y_diff  landing_x_diff  landing_y_diff  teammate_flag  \
0        -7.90138        4.019559      -15.097331              0   
1        -7.90138        4.019559      -15.097331              0   
2        -7.90138        4.019559      -15.097331              0   
3        -7.90138        4.019559      -15.097331              0   
4        -7.90138        4.019559      -15.097331              0   
5        -7.90138        4.019559      -15.097331              1   
6        -7.90138        4.019559      -15.097331              1   
7        -7.90138        4.019559      -15.097331              1   
8        -7.90138        4.019559      -15.097331              1   
9        -7.90138        4.019559      -15.097331              1   
10        2.33515       14.141599       -4.860801              0   
11        2.33515       14.141599       -4.860801        

In [4]:
rebound_data.shape

(8629400, 26)

In [5]:
rebound_data2 = rebound_data[rebound_data["teammate_flag"] == 1]

In [6]:
rebound_data2.head(50)

Unnamed: 0 group   GAME_ID  GAME_EVENT_ID       play_id  play_num  \
5            6  test  21500001             84  215000010084         1   
6            7  test  21500001             84  215000010084         1   
7            8  test  21500001             84  215000010084         1   
8            9  test  21500001             84  215000010084         1   
9           10  test  21500001             84  215000010084         1   
15          16  test  21500001             84  215000010084         1   
16          17  test  21500001             84  215000010084         1   
17          18  test  21500001             84  215000010084         1   
18          19  test  21500001             84  215000010084         1   
19          20  test  21500001             84  215000010084         1   
25          26  test  21500001             84  215000010084         1   
26          27  test  21500001             84  215000010084         1   
27          28  test  21500001             84  215000010084         1   
28          29  test  21500001             84  215000010084         1   
29          30  test  21500001             84  215000010084         1   
35          36  test  21500001             84  215000010084         1   
36          37  test  21500001             84  215000010084         1   
37          38  test  21500001             84  215000010084         1   
38          39  test  21500001             84  215000010084         1   
39          40  test  21500001             84  215000010084         1   
45          46  test  21500001             84  215000010084         1   
46          47  test  21500001             84  215000010084         1   
47          48  test  21500001             84  215000010084         1   
48          49  test  21500001             84  215000010084         1   
49          50  test  21500001             84  215000010084         1   
50          51  test  21500001             84  215000010084         1   
51          52  test  21500001             84  215000010084         1   
52          53  test  21500001             84  215000010084         1   
53          54  test  21500001             84  215000010084         1   
54          55  test  21500001             84  215000010084         1   
60          61  test  21500001             84  215000010084         1   
61          62  test  21500001             84  215000010084         1   
62          63  test  21500001             84  215000010084         1   
63          64  test  21500001             84  215000010084         1   
64          65  test  21500001             84  215000010084         1   
70          71  test  21500001             84  215000010084         1   
71          72  test  21500001             84  215000010084         1   
72          73  test  21500001             84  215000010084         1   
73          74  test  21500001             84  215000010084         1   
74          75  test  21500001             84  215000010084         1   
80          81  test  21500001             84  215000010084         1   
81          82  test  21500001             84  215000010084         1   
82          83  test  21500001             84  215000010084         1   
83          84  test  21500001             84  215000010084         1   
84          85  test  21500001             84  215000010084         1   
90          91  test  21500001             84  215000010084         1   
91          92  test  21500001             84  215000010084         1   
92          93  test  21500001             84  215000010084         1   
93          94  test  21500001             84  215000010084         1   
94          95  test  21500001             84  215000010084         1   

    player_num1  player_num2  player_id1  player_id2  ...  basket_x_diff  \
5             1            6      202694      200794  ...        3.21419   
6             1            7      202694      201168  ...        3.21419   
7             1            8      202694      203471

In [7]:
rebound_data2.shape

(4314700, 26)

In [8]:
# adding a test feature
rebound_data2["direction_towards_landing"] = (np.array(rebound_data2["landing_x_diff"])* \
                                             np.array(rebound_data2["x_speed1"]) + \
                                             np.array(rebound_data2["landing_y_diff"])* \
                                             np.array(rebound_data2["y_speed1"]))/ \
                                             np.sqrt(np.array(rebound_data2["landing_x_diff"])**2 +
                                                    np.array(rebound_data2["landing_y_diff"])**2)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [9]:
rebound_data2["defense_flag"] = [int(x) for x in np.array(rebound_data2["player_num1"]) > 5]

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [10]:
rebound_data2["shooter_flag"] = [int(x) for x in np.array(rebound_data2["player_num1"]) == 10]

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [11]:
rebound_data2

Unnamed: 0       group   GAME_ID  GAME_EVENT_ID       play_id  \
5                 6        test  21500001             84  215000010084   
6                 7        test  21500001             84  215000010084   
7                 8        test  21500001             84  215000010084   
8                 9        test  21500001             84  215000010084   
9                10        test  21500001             84  215000010084   
...             ...         ...       ...            ...           ...   
8629390     8629391  validation  21500663            522  215006630522   
8629391     8629392  validation  21500663            522  215006630522   
8629392     8629393  validation  21500663            522  215006630522   
8629393     8629394  validation  21500663            522  215006630522   
8629394     8629395  validation  21500663            522  215006630522   

         play_num  player_num1  player_num2  player_id1  player_id2  ...  \
5               1            1            6      202694      200794  ...   
6               1            1            7      202694      201168  ...   
7               1            1            8      202694      203471  ...   
8               1            1            9      202694      203934  ...   
9               1            1           10      202694      200757  ...   
...           ...          ...          ...         ...         ...  ...   
8629390      5394           10            1     1626167      200765  ...   
8629391      5394           10            2     1626167      201954  ...   
8629392      5394           10            3     1626167      202326  ...   
8629393      5394           10            4     1626167      202341  ...   
8629394      5394           10            5     1626167     1626161  ...   

         landing_y_diff  teammate_flag  t_after_shot  x_speed1  y_speed1  \
5            -15.097331              1      2.882159 -0.982599 -0.232334   
6            -15.097331              1      2.882159 -0.982599 -0.232334   
7            -15.097331              1      2.882159 -0.982599 -0.232334   
8            -15.097331              1      2.882159 -0.982599 -0.232334   
9            -15.097331              1      2.882159 -0.982599 -0.232334   
...                 ...            ...           ...       ...       ...   
8629390       -2.099809              1      2.763710 -0.142951  1.003859   
8629391       -2.099809              1      2.763710 -0.142951  1.003859   
8629392       -2.099809              1      2.763710 -0.142951  1.003859   
8629393       -2.099809              1      2.763710 -0.142951  1.003859   
8629394       -2.099809              1      2.763710 -0.142951  1.003859   

         position_num  position_diff  direction_towards_landing  defense_flag  \
5                   1              0                  -0.028291             0   
6                   1             -1                  -0.028291             0   
7                   1              1                  -0.028291             0   
8                   1              0                  -0.028291             0   
9                   1              0                  -0.028291             0   
...               ...            ...                        ...           ...   
8629390             2              2                  -0.302615             1   
8629391             2              2                  -0.302615             1   
8629392             2              0                  -0.302615             1   
8629393             2              1                  -0.302615             1   
8629394             2              0                  -0.302615             1   

         shooter_flag  
5                   0  
6                   0  
7                   0  
8                   0  
9                   0  
...               ...  
8629390             1  
8629391             1  
8629392             1  
8629393             1  
8629394             1  

[4314700 rows x 29 columns]

In [12]:
target_data = pd.read_csv("~/Desktop/Deep_Learning/nba-movement-data/rebounding_data/data_sets/landing_isotropic_target_augmented.csv")

In [13]:
target_data.head(10)

Unnamed: 0 group   GAME_ID  GAME_EVENT_ID  target
0           1  test  21500001             84       3
1           2  test  21500001             96       4
2           3  test  21500001            106      11
3           4  test  21500001            195      12
4           5  test  21500001            262      11
5           6  test  21500001            283       8
6           7  test  21500001            288       2
7           8  test  21500001            319       2
8           9  test  21500001            385       2
9          10  test  21500001            395       4

In [14]:
target_data["target"].max()

12

In [15]:
target_data.shape

(86294, 5)

# Formatting the Data

In [16]:
rebound_data2.shape

(4314700, 29)

In [17]:
rebound_data2.columns

Index(['Unnamed: 0', 'group', 'GAME_ID', 'GAME_EVENT_ID', 'play_id',
       'play_num', 'player_num1', 'player_num2', 'player_id1', 'player_id2',
       'x_diff', 'y_diff', 'x_speed_diff', 'y_speed_diff', 'shooter_x_diff',
       'shooter_y_diff', 'basket_x_diff', 'basket_y_diff', 'landing_x_diff',
       'landing_y_diff', 'teammate_flag', 't_after_shot', 'x_speed1',
       'y_speed1', 'position_num', 'position_diff',
       'direction_towards_landing', 'defense_flag', 'shooter_flag'],
      dtype='object')

In [242]:
def create_x(data, nfeatures):
    # creating a numpy tensor to hold the play data
    np_mat = np.array(data.drop(['Unnamed: 0','GAME_ID', 'GAME_EVENT_ID', 'play_id', 'player_id1','player_id2',
                                    'teammate_flag', 't_after_shot',"group"],
                               axis = 1))
    
    # setting parameters
    ngames = np.max(np.array(data['play_num']))
    nPlayers = 10
    nOpponents = 5
    
    # initializing the tensor
    np_tensor = np.zeros((ngames, nPlayers, nOpponents, nfeatures))
    
    for row in range(len(np_mat)):
        np_tensor[int(np_mat[row][0]) - 1][int(np_mat[row][1]) - 1][(int(np_mat[row][2]) - 1)%5] = np_mat[row][3:]
    
    np_tensor = np_tensor.astype('float32')
    
    return(np_tensor)

In [243]:
X_train = create_x(data = rebound_data2[(rebound_data2["group"] == "training") & (rebound_data2["GAME_ID"] <= 200000000)],
                  nfeatures = 17)

In [244]:
X_train.shape

(50338, 10, 5, 17)

In [245]:
X_train[0][0][0]

array([  6.27539  ,  18.24912  ,  -1.2883896,   0.6665976,  -0.6375   ,
       -15.46007  ,  13.60573  ,  -3.14684  ,  -3.6140425, -11.502322 ,
        -0.2276094,   0.7418832,   1.       ,   1.       ,  -0.6395424,
         0.       ,   0.       ], dtype=float32)

In [246]:
X_validation = create_x(data = rebound_data2[rebound_data2["group"] == "validation"],
                  nfeatures = 17)

In [247]:
X_validation.shape

(5394, 10, 5, 17)

In [248]:
X_validation[0][0][0]

array([-14.27714   ,  25.36597   ,  -0.9067038 ,  -2.7888439 ,
        14.94922   ,   7.32947   ,  14.04592   ,   5.60891   ,
         8.115526  ,   6.4308333 ,   0.3743706 ,  -2.0724113 ,
         0.        ,   0.        ,  -0.99367774,   0.        ,
         0.        ], dtype=float32)

In [249]:
X_test = create_x(data = rebound_data2[rebound_data2["group"] == "test"],
                  nfeatures = 17)

In [250]:
X_test.shape

(5393, 10, 5, 17)

In [251]:
def create_y(data):
    targets = np.array(data["target"])
    
    y = np.zeros((targets.shape[0], 12))
    for idx, target in enumerate(list(targets)):
        y[idx][target - 1] = 1
    
    return(y)

In [252]:
y_train = create_y(data = target_data[(target_data["group"] == "training") & (target_data["GAME_ID"] < 200000000)])

In [253]:
y_train.shape

(50338, 12)

In [254]:
y_train[0]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [255]:
y_validation = create_y(data = target_data[target_data["group"] == "validation"])

In [256]:
y_validation.shape

(5394, 12)

In [257]:
y_test = create_y(data = target_data[target_data["group"] == "test"])

In [258]:
y_test.shape

(5393, 12)

In [259]:
y_validation[0]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

# REMOVING TEAM REBOUNDS

In [260]:
# training remove
indices_keep = np.sum(y_train[:, 10:], axis = 1) < 1
y_train2 = y_train[indices_keep]
y_train2 = y_train2[:, 0:10]
X_train2 = X_train[indices_keep]

In [261]:
y_train2.shape, X_train2.shape

((46374, 10), (46374, 10, 5, 17))

In [262]:
# validation remove
indices_keep = np.sum(y_validation[:, 10:], axis = 1) < 1
y_validation2 = y_validation[indices_keep]
y_validation2 = y_validation2[:, 0:10]
X_validation2 = X_validation[indices_keep]

In [263]:
y_validation2.shape, X_validation2.shape

((4941, 10), (4941, 10, 5, 17))

In [264]:
# test remove
indices_keep = np.sum(y_test[:, 10:], axis = 1) < 1
y_test2 = y_test[indices_keep]
y_test2 = y_test2[:, 0:10]
X_test2 = X_test[indices_keep]

In [265]:
y_test2.shape, X_test2.shape

((4961, 10), (4961, 10, 5, 17))

# Training a Convolutional Neural Network Model

In [50]:
sample = np.random.choice(len(X_train), 10000, replace = False)

In [106]:
X_train_sample = X_train[sample]
y_train_sample = y_train[sample]

In [567]:
model = tf.keras.Sequential()

In [568]:
model.add(layers.Conv2D(120, 
                        kernel_size=(1,1), 
                        strides=(1,1), 
                        input_shape = (10,5,17)))
model.add(layers.Activation('relu'))
# model.add(layers.BatchNormalization())
model.add(layers.Dropout(0.2))
model.add(layers.Conv2D(60, 
                        kernel_size=(1,1), 
                        strides=(1,1)))
model.add(layers.Activation('relu'))
model.add(layers.BatchNormalization())
model.add(layers.Conv1D(120, 
                         kernel_size=1, 
                         strides=1))
model.add(layers.Activation('relu'))
# model.add(layers.BatchNormalization())
model.add(layers.Dropout(0.2))

import tensorflow.keras.backend as K

def channelPool(x):
    return .5*K.max(x,axis=2) + .5*K.mean(x,axis=2)

model.add(layers.Lambda(channelPool))

In [569]:
model.add(layers.BatchNormalization())
model.add(layers.Conv1D(50, 
                        kernel_size=1, 
                        strides=1))
model.add(layers.Activation('relu'))
model.add(layers.Dropout(0.2))
model.add(layers.Conv1D(100, 
                        kernel_size=1, 
                        strides=1))
model.add(layers.Activation('relu'))
model.add(layers.BatchNormalization())
model.add(layers.Conv1D(1, 
                         kernel_size=1, 
                         strides=1))
model.add(layers.Flatten())
model.add(layers.Activation('softmax'))

In [570]:
model.summary()

Model: "sequential_22"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_44 (Conv2D)           (None, 10, 5, 120)        2160      
_________________________________________________________________
activation_139 (Activation)  (None, 10, 5, 120)        0         
_________________________________________________________________
dropout_66 (Dropout)         (None, 10, 5, 120)        0         
_________________________________________________________________
conv2d_45 (Conv2D)           (None, 10, 5, 60)         7260      
_________________________________________________________________
activation_140 (Activation)  (None, 10, 5, 60)         0         
_________________________________________________________________
batch_normalization_66 (Batc (None, 10, 5, 60)         240       
_________________________________________________________________
conv1d_88 (Conv1D)           (None, 10, 5, 120)      

In [544]:
from tensorflow.keras.metrics import BinaryAccuracy

In [307]:
test = tf.constant([[0,0,1,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,1,0,0,0]])

In [115]:
dir(tf.keras.backend)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'abs',
 'all',
 'any',
 'arange',
 'argmax',
 'argmin',
 'backend',
 'batch_dot',
 'batch_flatten',
 'batch_get_value',
 'batch_normalization',
 'batch_set_value',
 'bias_add',
 'binary_crossentropy',
 'cast',
 'cast_to_floatx',
 'categorical_crossentropy',
 'clear_session',
 'clip',
 'concatenate',
 'constant',
 'conv1d',
 'conv2d',
 'conv2d_transpose',
 'conv3d',
 'cos',
 'count_params',
 'ctc_batch_cost',
 'ctc_decode',
 'ctc_label_dense_to_sparse',
 'cumprod',
 'cumsum',
 'depthwise_conv2d',
 'dot',
 'dropout',
 'dtype',
 'elu',
 'epsilon',
 'equal',
 'eval',
 'exp',
 'expand_dims',
 'eye',
 'flatten',
 'floatx',
 'foldl',
 'foldr',
 'function',
 'gather',
 'get_uid',
 'get_value',
 'gradients',
 'greater',
 'greater_equal',
 'hard_sigmoid',
 'image_data_format',
 'in_test_phase',
 'in_top_k',
 'in_train_phase',
 'int_shape',
 'is_keras_tensor',
 

In [395]:
test

<tf.Tensor: shape=(2, 10), dtype=int32, numpy=
array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]], dtype=int32)>

In [410]:
test2 = tf.constant([[0, 0,.8,0,0,0,0,0,0,.2],
                    [.8, 0,0,0,0,0,0,0,0,.2]])

In [503]:
1 -K.square(K.transpose(test2))

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[1.        , 0.35999995],
       [1.        , 1.        ],
       [0.35999995, 1.        ],
       [1.        , 1.        ],
       [1.        , 1.        ],
       [1.        , 1.        ],
       [1.        , 1.        ],
       [1.        , 1.        ],
       [1.        , 1.        ],
       [0.96      , 0.96      ]], dtype=float32)>

In [442]:
test2[0]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0. , 0. , 0.8, 0. , 0. , 0. , 0. , 0. , 0. , 0.2], dtype=float32)>

In [445]:
1 - K.mean(tf.linalg.diag_part(K.dot(test2, K.transpose(tf.dtypes.cast(test, tf.float32)))))

<tf.Tensor: shape=(), dtype=float32, numpy=0.6>

In [392]:
K.batch_flatten(K.sum(test[:,0:5], axis = 1))

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [0]], dtype=int32)>

In [156]:
m = BinaryAccuracy()
m.update_state(K.batch_flatten(K.sum(test[:,0:5], axis = 1)), 
               K.batch_flatten(K.sum(test2[:,0:5], axis = 1)))
K.eval(m.result())

0.5

In [571]:
import tensorflow.keras.backend as K
def playerteamopt(y_true, y_pred):
    y_true_team = K.batch_flatten(K.sum(y_true[:,0:5], axis = 1))
    y_pred_team = K.batch_flatten(K.sum(y_pred[:,0:5], axis = 1))
#     return 0.5*tf.keras.backend.categorical_crossentropy(y_true, y_pred) + \
#            0.5*tf.keras.backend.binary_crossentropy(y_true_team, y_pred_team)
    
#     return 0.5*(1 - K.mean(tf.linalg.diag_part(K.dot(y_pred, K.transpose(tf.dtypes.cast(y_true, tf.float32)))))) + \
#            0.5*tf.keras.backend.binary_crossentropy(y_true_team, y_pred_team)
    
    return 0.5*(K.mean(K.pow(1 - tf.linalg.diag_part(K.dot(y_pred, K.transpose(tf.dtypes.cast(y_true, tf.float32)))), 1.5))) + \
            0.5*tf.keras.backend.binary_crossentropy(y_true_team, y_pred_team)


In [572]:
def better_crossentropy(y_true, y_pred):
    return 1 - K.mean(tf.linalg.diag_part(K.dot(y_pred, K.transpose(tf.dtypes.cast(y_true, tf.float32)))))

In [573]:
def team_crossentropy(y_true, y_pred):
    y_true_team = K.batch_flatten(K.sum(y_true[:,0:5], axis = 1))
    y_pred_team = K.batch_flatten(K.sum(y_pred[:,0:5], axis = 1))
    return tf.keras.backend.binary_crossentropy(y_true_team, y_pred_team)

In [574]:
def def_probs(y_true, y_pred):
    y_pred_team = K.sum(y_pred[:,0:5], axis = 1)
    return K.mean(y_pred_team)

In [575]:
def def_freq(y_true, y_pred):
    y_true_team = K.sum(y_true[:,0:5], axis = 1)
    return K.mean(y_true_team)

In [576]:
def top_k_categorical_accuracy2(y_true, y_pred, k=2):
    return K.mean(K.in_top_k(y_pred, K.argmax(y_true, axis=-1), k), axis=-1)

def top_k_categorical_accuracy3(y_true, y_pred, k=3):
    return K.mean(K.in_top_k(y_pred, K.argmax(y_true, axis=-1), k), axis=-1)

In [577]:
from tensorflow.keras.optimizers import Adam
model.compile(loss=[playerteamopt], metrics=['categorical_accuracy',
                                            top_k_categorical_accuracy3, team_crossentropy,
                                            def_probs, def_freq], 
              optimizer= 'adam')

In [578]:
history = model.fit(x = X_train2, y = y_train2,
                   validation_data = (X_validation2, y_validation2),
                   epochs = 50,
                   # callbacks=callbacks, # Early stopping
                   verbose = 1)

Epoch 1/50
1450/1450 [==============================] - 24s 16ms/step - loss: 0.5384 - categorical_accuracy: 0.3946 - top_k_categorical_accuracy3: 0.7589 - team_crossentropy: 0.4790 - def_probs: 0.8139 - def_freq: 0.8101 - val_loss: 0.5125 - val_categorical_accuracy: 0.4501 - val_top_k_categorical_accuracy3: 0.7840 - val_team_crossentropy: 0.4508 - val_def_probs: 0.8090 - val_def_freq: 0.8084
Epoch 2/50
1450/1450 [==============================] - 24s 16ms/step - loss: 0.5093 - categorical_accuracy: 0.4421 - top_k_categorical_accuracy3: 0.7936 - team_crossentropy: 0.4609 - def_probs: 0.8225 - def_freq: 0.8102 - val_loss: 0.5059 - val_categorical_accuracy: 0.4525 - val_top_k_categorical_accuracy3: 0.7877 - val_team_crossentropy: 0.4429 - val_def_probs: 0.7847 - val_def_freq: 0.8084
Epoch 3/50
1450/1450 [==============================] - 27s 19ms/step - loss: 0.5012 - categorical_accuracy: 0.4521 - top_k_categorical_accuracy3: 0.7990 - team_crossentropy: 0.4567 - def_probs: 0.8234 - def_

1450/1450 [==============================] - 37s 26ms/step - loss: 0.4716 - categorical_accuracy: 0.4862 - top_k_categorical_accuracy3: 0.8179 - team_crossentropy: 0.4324 - def_probs: 0.8251 - def_freq: 0.8101 - val_loss: 0.4878 - val_categorical_accuracy: 0.4778 - val_top_k_categorical_accuracy3: 0.8006 - val_team_crossentropy: 0.4349 - val_def_probs: 0.7909 - val_def_freq: 0.8084
Epoch 22/50
1450/1450 [==============================] - 27s 19ms/step - loss: 0.4716 - categorical_accuracy: 0.4854 - top_k_categorical_accuracy3: 0.8184 - team_crossentropy: 0.4330 - def_probs: 0.8240 - def_freq: 0.8101 - val_loss: 0.4903 - val_categorical_accuracy: 0.4805 - val_top_k_categorical_accuracy3: 0.8079 - val_team_crossentropy: 0.4314 - val_def_probs: 0.7856 - val_def_freq: 0.8084
Epoch 23/50
1450/1450 [==============================] - 28s 19ms/step - loss: 0.4711 - categorical_accuracy: 0.4850 - top_k_categorical_accuracy3: 0.8182 - team_crossentropy: 0.4321 - def_probs: 0.8250 - def_freq: 0.8

Epoch 42/50
1450/1450 [==============================] - 26s 18ms/step - loss: 0.4614 - categorical_accuracy: 0.4970 - top_k_categorical_accuracy3: 0.8206 - team_crossentropy: 0.4226 - def_probs: 0.8246 - def_freq: 0.8100 - val_loss: 0.4835 - val_categorical_accuracy: 0.4780 - val_top_k_categorical_accuracy3: 0.8029 - val_team_crossentropy: 0.4361 - val_def_probs: 0.7869 - val_def_freq: 0.8084
Epoch 43/50
1450/1450 [==============================] - 25s 17ms/step - loss: 0.4609 - categorical_accuracy: 0.4946 - top_k_categorical_accuracy3: 0.8207 - team_crossentropy: 0.4216 - def_probs: 0.8224 - def_freq: 0.8100 - val_loss: 0.4789 - val_categorical_accuracy: 0.4782 - val_top_k_categorical_accuracy3: 0.8051 - val_team_crossentropy: 0.4357 - val_def_probs: 0.8208 - val_def_freq: 0.8084
Epoch 44/50
1450/1450 [==============================] - 25s 18ms/step - loss: 0.4599 - categorical_accuracy: 0.4953 - top_k_categorical_accuracy3: 0.8208 - team_crossentropy: 0.4207 - def_probs: 0.8242 - d

In [553]:
model.evaluate(X_test2, y_test2)

156/156 [==============================] - 1s 4ms/step - loss: 0.4477 - categorical_accuracy: 0.4914 - top_k_categorical_accuracy3: 0.8215 - team_crossentropy: 0.4286 - def_probs: 0.7850 - def_freq: 0.8089


[0.44765302538871765,
 0.49143317341804504,
 0.8215144276618958,
 0.42864367365837097,
 0.7850418090820312,
 0.8088942170143127]

In [ ]:
# visualize the first prediction's explanation (use matplotlib=True to avoid Javascript)
shap.force_plot(explainer.expected_value, shap_values[0,:], X_train2.iloc[0,:])

# Feature Importance (Permutation)

In [137]:
import random

In [169]:
nfeatures = X_train2.shape[-1]
nSamples = X_train2.shape[0]
X_train_feature_imp = np.zeros(X_train2.shape)
accuracy = []
for iCnt in range(nfeatures):
    X_train_feature_imp = X_train2.copy()
    for jCnt in range(nSamples):
        jumbled_vals = X_train2[:,:,:,iCnt][jCnt].ravel()
        jumbled_vals2 = random.sample(list(jumbled_vals), len(jumbled_vals))
        jumbled_vals3 = np.array(jumbled_vals2).reshape(X_train2[:,:,:,iCnt][jCnt].shape)
        X_train_feature_imp[:,:,:,iCnt][jCnt] = jumbled_vals3
    
    # training the model
    model = tf.keras.Sequential()

    model.add(layers.Conv2D(100, 
                            kernel_size=(1,1), 
                            strides=(1,1), 
                            input_shape = (10,5,13)))
    model.add(layers.Activation('relu'))
    model.add(layers.Dropout(0.2))
    model.add(layers.Conv2D(50, 
                            kernel_size=(1,1), 
                            strides=(1,1)))
    model.add(layers.Activation('relu'))
    model.add(layers.Conv1D(100, 
                             kernel_size=1, 
                             strides=1))
    model.add(layers.Activation('relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.Dropout(0.2))

    import tensorflow.keras.backend as K

    def channelPool(x):
        return .5*K.max(x,axis=2) + .5*K.mean(x,axis=2)

    model.add(layers.Lambda(channelPool))

    model.add(layers.BatchNormalization())
    model.add(layers.Conv1D(100, 
                            kernel_size=1, 
                            strides=1))
    model.add(layers.Activation('relu'))
    model.add(layers.Dropout(0.2))
    model.add(layers.Conv1D(50, 
                            kernel_size=1, 
                            strides=1))
    model.add(layers.Activation('relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.Conv1D(1, 
                             kernel_size=1, 
                             strides=1))
    model.add(layers.Activation('relu'))

    model.add(layers.Flatten())
    model.add(layers.Activation('softmax'))
    
    model.compile(loss=['categorical_crossentropy'], metrics=['categorical_accuracy', top_k_categorical_accuracy2,
                                                    top_k_categorical_accuracy3], optimizer='adam')
    
    history = model.fit(x = X_train_feature_imp, y = y_train2,
                   validation_data = (X_validation2, y_validation2),
                   epochs = 5,
                   # callbacks=callbacks, # Early stopping
                   verbose = 1)
    
    accuracy += [history.history['categorical_accuracy'][-1]]

Epoch 1/5
1645/1645 [==============================] - 24s 15ms/step - loss: 1.7222 - categorical_accuracy: 0.3665 - top_k_categorical_accuracy2: 0.5888 - top_k_categorical_accuracy3: 0.7362 - val_loss: 1.6047 - val_categorical_accuracy: 0.4253 - val_top_k_categorical_accuracy2: 0.6465 - val_top_k_categorical_accuracy3: 0.7727
Epoch 2/5
1645/1645 [==============================] - 24s 15ms/step - loss: 1.6065 - categorical_accuracy: 0.4188 - top_k_categorical_accuracy2: 0.6407 - top_k_categorical_accuracy3: 0.7780 - val_loss: 1.5802 - val_categorical_accuracy: 0.4365 - val_top_k_categorical_accuracy2: 0.6484 - val_top_k_categorical_accuracy3: 0.7787
Epoch 3/5
1645/1645 [==============================] - 24s 15ms/step - loss: 1.5859 - categorical_accuracy: 0.4309 - top_k_categorical_accuracy2: 0.6506 - top_k_categorical_accuracy3: 0.7838 - val_loss: 1.5661 - val_categorical_accuracy: 0.4416 - val_top_k_categorical_accuracy2: 0.6562 - val_top_k_categorical_accuracy3: 0.7828
Epoch 4/5
164

Epoch 1/5
1645/1645 [==============================] - 24s 15ms/step - loss: 1.6946 - categorical_accuracy: 0.3832 - top_k_categorical_accuracy2: 0.6001 - top_k_categorical_accuracy3: 0.7462 - val_loss: 1.5969 - val_categorical_accuracy: 0.4290 - val_top_k_categorical_accuracy2: 0.6490 - val_top_k_categorical_accuracy3: 0.7799
Epoch 2/5
1645/1645 [==============================] - 24s 14ms/step - loss: 1.6068 - categorical_accuracy: 0.4200 - top_k_categorical_accuracy2: 0.6436 - top_k_categorical_accuracy3: 0.7770 - val_loss: 1.5893 - val_categorical_accuracy: 0.4344 - val_top_k_categorical_accuracy2: 0.6485 - val_top_k_categorical_accuracy3: 0.7767
Epoch 3/5
1645/1645 [==============================] - 24s 14ms/step - loss: 1.5878 - categorical_accuracy: 0.4307 - top_k_categorical_accuracy2: 0.6507 - top_k_categorical_accuracy3: 0.7832 - val_loss: 1.5811 - val_categorical_accuracy: 0.4360 - val_top_k_categorical_accuracy2: 0.6581 - val_top_k_categorical_accuracy3: 0.7846
Epoch 4/5
164

In [170]:
accuracy

[0.44033822417259216,
 0.4342770278453827,
 0.4397681951522827,
 0.43771612644195557,
 0.4378301203250885,
 0.4372031092643738,
 0.43919816613197327,
 0.431939959526062,
 0.42908987402915955,
 0.3787573575973511,
 0.43467605113983154,
 0.4331369996070862,
 0.42967888712882996]

In [176]:
rebound_data2.drop(['Unnamed: 0','GAME_ID', 'GAME_EVENT_ID', 'play_id', 'player_id1','player_id2',
                                    'teammate_flag', 't_after_shot',"group"], axis = 1).columns

Index(['play_num', 'player_num1', 'player_num2', 'x_diff', 'y_diff',
       'x_speed_diff', 'y_speed_diff', 'shooter_x_diff', 'shooter_y_diff',
       'basket_x_diff', 'basket_y_diff', 'landing_x_diff', 'landing_y_diff',
       'x_speed1', 'y_speed1', 'position_num'],
      dtype='object')

# Finding Plays Of Interest

In [140]:
rebound_data[rebound_data["play_id"] == 215004920018]

Unnamed: 0     group   GAME_ID  GAME_EVENT_ID       play_id  \
2825300     2825301  training  21500492             18  215004920018   
2825301     2825302  training  21500492             18  215004920018   
2825302     2825303  training  21500492             18  215004920018   
2825303     2825304  training  21500492             18  215004920018   
2825304     2825305  training  21500492             18  215004920018   
...             ...       ...       ...            ...           ...   
2825395     2825396  training  21500492             18  215004920018   
2825396     2825397  training  21500492             18  215004920018   
2825397     2825398  training  21500492             18  215004920018   
2825398     2825399  training  21500492             18  215004920018   
2825399     2825400  training  21500492             18  215004920018   

         play_num  player_num1  player_num2  player_id1  player_id2  ...  \
2825300     22089            1            1      101107      101107  ...   
2825301     22089            1            2      101107      201587  ...   
2825302     22089            1            3      101107      202689  ...   
2825303     22089            1            4      101107      203469  ...   
2825304     22089            1            5      101107      203798  ...   
...           ...          ...          ...         ...         ...  ...   
2825395     22089           10            6      201942        2449  ...   
2825396     22089           10            7      201942      200768  ...   
2825397     22089           10            8      201942      201960  ...   
2825398     22089           10            9      201942      202685  ...   
2825399     22089           10           10      201942      201942  ...   

         shooter_y_diff  basket_x_diff  basket_y_diff  landing_x_diff  \
2825300       -16.85665        0.13216      -11.13744       -0.593802   
2825301       -16.85665        0.13216      -11.13744       -0.593802   
2825302       -16.85665        0.13216      -11.13744       -0.593802   
2825303       -16.85665        0.13216      -11.13744       -0.593802   
2825304       -16.85665        0.13216      -11.13744       -0.593802   
...                 ...            ...            ...             ...   
2825395         0.00000        5.51369        5.71921        4.787728   
2825396         0.00000        5.51369        5.71921        4.787728   
2825397         0.00000        5.51369        5.71921        4.787728   
2825398         0.00000        5.51369        5.71921        4.787728   
2825399         0.00000        5.51369        5.71921        4.787728   

         landing_y_diff  teammate_flag  t_after_shot  x_speed1  y_speed1  \
2825300       -7.914302              0      2.363303  0.195605  1.121435   
2825301       -7.914302              0      2.363303  0.195605  1.121435   
2825302       -7.914302              0      2.363303  0.195605  1.121435   
2825303       -7.914302              0      2.363303  0.195605  1.121435   
2825304       -7.914302              0      2.363303  0.195605  1.121435   
...                 ...            ...           ...       ...       ...   
2825395        8.942348              0      2.363303 -2.945054  0.201397   
2825396        8.942348              0      2.363303 -2.945054  0.201397   
2825397        8.942348              0      2.363303 -2.945054  0.201397   
2825398        8.942348              0      2.363303 -2.945054  0.201397   
2825399        8.942348              0      2.363303 -2.945054  0.201397   

         position_num  
2825300             1  
2825301             1  
2825302             1  
2825303             1  
2825304             1  
...               ...  
2825395             0  
2825396             0  
2825397             0  
2825398             0  
2825399             0  

[100 rows x 25 columns]

In [141]:
rebound_data[rebound_data["play_id"] == 1215004920018]

Unnamed: 0     group    GAME_ID  GAME_EVENT_ID        play_id  \
5702500     5702501  training  121500492             18  1215004920018   
5702501     5702502  training  121500492             18  1215004920018   
5702502     5702503  training  121500492             18  1215004920018   
5702503     5702504  training  121500492             18  1215004920018   
5702504     5702505  training  121500492             18  1215004920018   
...             ...       ...        ...            ...            ...   
5702595     5702596  training  121500492             18  1215004920018   
5702596     5702597  training  121500492             18  1215004920018   
5702597     5702598  training  121500492             18  1215004920018   
5702598     5702599  training  121500492             18  1215004920018   
5702599     5702600  training  121500492             18  1215004920018   

         play_num  player_num1  player_num2  player_id1  player_id2  ...  \
5702500     50861            1            1      101107      101107  ...   
5702501     50861            1            2      101107      201587  ...   
5702502     50861            1            3      101107      202689  ...   
5702503     50861            1            4      101107      203469  ...   
5702504     50861            1            5      101107      203798  ...   
...           ...          ...          ...         ...         ...  ...   
5702595     50861           10            6      201942        2449  ...   
5702596     50861           10            7      201942      200768  ...   
5702597     50861           10            8      201942      201960  ...   
5702598     50861           10            9      201942      202685  ...   
5702599     50861           10           10      201942      201942  ...   

         shooter_y_diff  basket_x_diff  basket_y_diff  landing_x_diff  \
5702500        16.85665        0.13216       11.13744       -0.593802   
5702501        16.85665        0.13216       11.13744       -0.593802   
5702502        16.85665        0.13216       11.13744       -0.593802   
5702503        16.85665        0.13216       11.13744       -0.593802   
5702504        16.85665        0.13216       11.13744       -0.593802   
...                 ...            ...            ...             ...   
5702595         0.00000        5.51369       -5.71921        4.787728   
5702596         0.00000        5.51369       -5.71921        4.787728   
5702597         0.00000        5.51369       -5.71921        4.787728   
5702598         0.00000        5.51369       -5.71921        4.787728   
5702599         0.00000        5.51369       -5.71921        4.787728   

         landing_y_diff  teammate_flag  t_after_shot  x_speed1  y_speed1  \
5702500        7.914302              0      2.363303  0.195605 -1.121435   
5702501        7.914302              0      2.363303  0.195605 -1.121435   
5702502        7.914302              0      2.363303  0.195605 -1.121435   
5702503        7.914302              0      2.363303  0.195605 -1.121435   
5702504        7.914302              0      2.363303  0.195605 -1.121435   
...                 ...            ...           ...       ...       ...   
5702595       -8.942348              0      2.363303 -2.945054 -0.201397   
5702596       -8.942348              0      2.363303 -2.945054 -0.201397   
5702597       -8.942348              0      2.363303 -2.945054 -0.201397   
5702598       -8.942348              0      2.363303 -2.945054 -0.201397   
5702599       -8.942348              0      2.363303 -2.945054 -0.201397   

         position_num  
5702500             1  
5702501             1  
5702502             1  
5702503             1  
5702504             1  
...               ...  
5702595             0  
5702596             0  
5702597             0  
5702598             0  
5702599             0  

[100 rows x 25 columns]

In [142]:
rebound_data[rebound_data["play_id"] == 2215004920018]

Unnamed: 0     group    GAME_ID  GAME_EVENT_ID        play_id  \
8579700     8579701  training  221500492             18  2215004920018   
8579701     8579702  training  221500492             18  2215004920018   
8579702     8579703  training  221500492             18  2215004920018   
8579703     8579704  training  221500492             18  2215004920018   
8579704     8579705  training  221500492             18  2215004920018   
...             ...       ...        ...            ...            ...   
8579795     8579796  training  221500492             18  2215004920018   
8579796     8579797  training  221500492             18  2215004920018   
8579797     8579798  training  221500492             18  2215004920018   
8579798     8579799  training  221500492             18  2215004920018   
8579799     8579800  training  221500492             18  2215004920018   

         play_num  player_num1  player_num2  player_id1  player_id2  ...  \
8579700     79633            1            1      203798      203798  ...   
8579701     79633            1            2      203798      203469  ...   
8579702     79633            1            3      203798      202689  ...   
8579703     79633            1            4      203798      201587  ...   
8579704     79633            1            5      203798      101107  ...   
...           ...          ...          ...         ...         ...  ...   
8579795     79633           10            6      201942      202685  ...   
8579796     79633           10            7      201942      201960  ...   
8579797     79633           10            8      201942      200768  ...   
8579798     79633           10            9      201942        2449  ...   
8579799     79633           10           10      201942      201942  ...   

         shooter_y_diff  basket_x_diff  basket_y_diff  landing_x_diff  \
8579700        -1.66049        6.48310        4.05872        5.757138   
8579701        -1.66049        6.48310        4.05872        5.757138   
8579702        -1.66049        6.48310        4.05872        5.757138   
8579703        -1.66049        6.48310        4.05872        5.757138   
8579704        -1.66049        6.48310        4.05872        5.757138   
...                 ...            ...            ...             ...   
8579795         0.00000        5.51369        5.71921        4.787728   
8579796         0.00000        5.51369        5.71921        4.787728   
8579797         0.00000        5.51369        5.71921        4.787728   
8579798         0.00000        5.51369        5.71921        4.787728   
8579799         0.00000        5.51369        5.71921        4.787728   

         landing_y_diff  teammate_flag  t_after_shot  x_speed1  y_speed1  \
8579700        7.281858              0      2.363303 -2.320519  0.314935   
8579701        7.281858              0      2.363303 -2.320519  0.314935   
8579702        7.281858              0      2.363303 -2.320519  0.314935   
8579703        7.281858              0      2.363303 -2.320519  0.314935   
8579704        7.281858              0      2.363303 -2.320519  0.314935   
...                 ...            ...           ...       ...       ...   
8579795        8.942348              0      2.363303 -2.945054  0.201397   
8579796        8.942348              0      2.363303 -2.945054  0.201397   
8579797        8.942348              0      2.363303 -2.945054  0.201397   
8579798        8.942348              0      2.363303 -2.945054  0.201397   
8579799        8.942348              0      2.363303 -2.945054  0.201397   

         position_num  
8579700             1  
8579701             1  
8579702             1  
8579703             1  
8579704             1  
...               ...  
8579795             0  
8579796             0  
8579797             0  
8579798             0  
8579799             0  

[100 rows x 25 columns]

In [58]:
model.predict(X_train[3117:3118])[0]

array([0.10680375, 0.08814253, 0.02249029, 0.04032568, 0.02493255,
       0.10171559, 0.05663201, 0.19644837, 0.22250251, 0.07254244,
       0.03884362, 0.02862073], dtype=float32)

In [93]:
model.predict(X_train[5318:5319])[0]

array([0.08682196, 0.14500305, 0.0254006 , 0.0793903 , 0.05447052,
       0.09237194, 0.07975851, 0.13644896, 0.20426658, 0.01988647,
       0.04775301, 0.02842814], dtype=float32)

In [121]:
model.predict(X_train[5318:5319])[0]

array([0.11727763, 0.12979652, 0.02756063, 0.05051339, 0.06298785,
       0.06191048, 0.11469693, 0.11827736, 0.17995417, 0.06017031,
       0.03991525, 0.03693951], dtype=float32)

In [204]:
model.predict(X_train[6499:6500])[0]

array([0.12492052, 0.16287728, 0.0106058 , 0.05008564, 0.03704832,
       0.11366668, 0.04412093, 0.20417666, 0.17917123, 0.00771315,
       0.04010834, 0.02550546], dtype=float32)

# Checking Results

In [475]:
# original play
model.predict(X_train2[0:1])[0]

array([0.08958714, 0.01003206, 0.33737174, 0.35016048, 0.00104053,
       0.0007547 , 0.00657394, 0.12054211, 0.00293896, 0.08099833],
      dtype=float32)

In [476]:
# flipped inputs
X_train2_ex = X_train2[0:1]

In [477]:
X_train2_ex[0][0][0]

array([  6.27539  ,  18.24912  ,  -1.2883896,   0.6665976,  -0.6375   ,
       -15.46007  ,  13.60573  ,  -3.14684  ,  -3.6140425, -11.502322 ,
        -0.2276094,   0.7418832,   1.       ,   1.       ,  -0.6395424,
         0.       ,   0.       ], dtype=float32)

In [478]:
X_train2_ex.shape

(1, 10, 5, 17)

In [479]:
X_train2_ex_flipped = np.zeros(X_train2_ex.shape)

In [480]:
for iCnt in range(10):
    for jCnt in range(5):
        X_train2_ex_flipped[0][iCnt][jCnt] = X_train2_ex[0][9-iCnt][4 - jCnt]

In [481]:
X_train2_ex_flipped[0][0][0]

array([ 9.11034012, 22.16423035, -0.50962561,  0.79758543,  0.        ,
        0.        , 14.24322987, 12.31322956, -2.97654247,  3.9577477 ,
        0.29702759,  0.30548581,  2.        ,  2.        ,  0.06561229,
        1.        ,  1.        ])

In [482]:
# original play
model.predict(X_train2[0:1])[0]

array([0.08958714, 0.01003206, 0.33737174, 0.35016048, 0.00104053,
       0.0007547 , 0.00657394, 0.12054211, 0.00293896, 0.08099833],
      dtype=float32)

In [483]:
model.predict(X_train2_ex_flipped)[0]

array([0.08099832, 0.00293896, 0.12054211, 0.00657394, 0.0007547 ,
       0.00104053, 0.35016048, 0.33737174, 0.01003206, 0.08958714],
      dtype=float32)

In [484]:
for iCnt in range(len(model.predict(X_train2_ex_flipped)[0])):
    print((model.predict(X_train2[0:1])[0][iCnt],
          model.predict(X_train2_ex_flipped)[0][9-iCnt]))

(0.089587145, 0.089587145)
(0.010032064, 0.010032062)
(0.33737174, 0.33737174)
(0.35016048, 0.35016048)
(0.0010405277, 0.0010405286)
(0.000754698, 0.00075469835)
(0.0065739406, 0.006573942)
(0.12054211, 0.12054211)
(0.0029389623, 0.0029389623)
(0.08099833, 0.080998324)


# Scoring Plays

In [52]:
score_data = pd.read_csv("~/Desktop/Deep_Learning/nba-movement-data/rebounding_data/data_sets/landing_isotropic_score_augmented2.csv")

In [53]:
score_data.shape

(3308900, 26)

In [54]:
score_data2 = score_data[score_data["teammate_flag"] == 1]

In [55]:
score_data2['play_num'] = [int(np.floor(x/50)) + 1 for x in range(0,len(score_data2["GAME_ID"]))]

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [56]:
# adding a test feature
score_data2["direction_towards_landing"] = (np.array(score_data2["landing_x_diff"])* \
                                             np.array(score_data2["x_speed1"]) + \
                                             np.array(score_data2["landing_y_diff"])* \
                                             np.array(score_data2["y_speed1"]))/ \
                                             np.sqrt(np.array(score_data2["landing_x_diff"])**2 +
                                                    np.array(score_data2["landing_y_diff"])**2)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [57]:
score_data2["defense_flag"] = [int(x) for x in np.array(score_data2["player_num1"]) > 5]

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [58]:
score_data2["shooter_flag"] = [int(x) for x in np.array(score_data2["player_num1"]) == 10]

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [59]:
score_data2

Unnamed: 0       group   GAME_ID  GAME_EVENT_ID       play_id  \
5                 6    training  21500001              8  215000010008   
6                 7    training  21500001              8  215000010008   
7                 8    training  21500001              8  215000010008   
8                 9    training  21500001              8  215000010008   
9                10    training  21500001              8  215000010008   
...             ...         ...       ...            ...           ...   
3308890     3308891  validation  21500663            522  215006630522   
3308891     3308892  validation  21500663            522  215006630522   
3308892     3308893  validation  21500663            522  215006630522   
3308893     3308894  validation  21500663            522  215006630522   
3308894     3308895  validation  21500663            522  215006630522   

         play_num  player_num1  player_num2  player_id1  player_id2  ...  \
5               1            1            6      101141        2594  ...   
6               1            1            7      101141      200794  ...   
7               1            1            8      101141      201952  ...   
8               1            1            9      101141      203145  ...   
9               1            1           10      101141      201143  ...   
...           ...          ...          ...         ...         ...  ...   
3308890     33089           10            1     1626167      200765  ...   
3308891     33089           10            2     1626167      201954  ...   
3308892     33089           10            3     1626167      202326  ...   
3308893     33089           10            4     1626167      202341  ...   
3308894     33089           10            5     1626167     1626161  ...   

         landing_y_diff  teammate_flag  t_after_shot  x_speed1  y_speed1  \
5            -11.502322              1      2.805424 -0.227609  0.741883   
6            -11.502322              1      2.805424 -0.227609  0.741883   
7            -11.502322              1      2.805424 -0.227609  0.741883   
8            -11.502322              1      2.805424 -0.227609  0.741883   
9            -11.502322              1      2.805424 -0.227609  0.741883   
...                 ...            ...           ...       ...       ...   
3308890       -2.099809              1      2.763710 -0.142951  1.003859   
3308891       -2.099809              1      2.763710 -0.142951  1.003859   
3308892       -2.099809              1      2.763710 -0.142951  1.003859   
3308893       -2.099809              1      2.763710 -0.142951  1.003859   
3308894       -2.099809              1      2.763710 -0.142951  1.003859   

         position_num  position_diff  direction_towards_landing  defense_flag  \
5                   1              1                  -0.639542             0   
6                   1              0                  -0.639542             0   
7                   1              1                  -0.639542             0   
8                   1              1                  -0.639542             0   
9                   1             -1                  -0.639542             0   
...               ...            ...                        ...           ...   
3308890             2              2                  -0.302615             1   
3308891             2              2                  -0.302615             1   
3308892             2              0                  -0.302615             1   
3308893             2              1                  -0.302615             1   
3308894             2              0                  -0.302615             1   

         shooter_flag  
5                   0  
6                   0  
7                   0  
8                   0  
9                   0  
...               ...  
3308890             1  
3308891             1  
3308892             1  
3308893             1  
3308894             1  

[1654450 rows x 29 columns]

In [485]:
X_score = create_x(data = score_data2,
                  nfeatures = 17)

In [486]:
X_score.shape

(33089, 10, 5, 17)

In [526]:
preds = model.predict(X_score)

In [527]:
preds.shape

(33089, 10)

In [528]:
preds[0]

array([0.10961451, 0.01288968, 0.40485987, 0.23503056, 0.00814281,
       0.0060834 , 0.01232912, 0.1355294 , 0.01530389, 0.06021676],
      dtype=float32)

In [529]:
column_names = ['p1', 'p2', 'p3','p4','p5','p6','p7','p8','p9','pshooter']

In [530]:
model_preds = pd.DataFrame(preds, columns = column_names)

In [531]:
model_preds

p1        p2        p3        p4        p5        p6        p7  \
0      0.109615  0.012890  0.404860  0.235031  0.008143  0.006083  0.012329   
1      0.154865  0.144697  0.099772  0.461496  0.001924  0.002698  0.000304   
2      0.007708  0.740597  0.177601  0.008221  0.000664  0.000197  0.027528   
3      0.078775  0.339698  0.440581  0.000027  0.126452  0.000088  0.000115   
4      0.320549  0.372308  0.178323  0.086942  0.037137  0.000599  0.000005   
...         ...       ...       ...       ...       ...       ...       ...   
33084  0.358843  0.005388  0.044533  0.019903  0.048663  0.356423  0.047905   
33085  0.000010  0.316702  0.001114  0.011671  0.331621  0.000642  0.297932   
33086  0.000494  0.000675  0.006073  0.012143  0.548592  0.005575  0.000085   
33087  0.000417  0.015195  0.919939  0.008853  0.000040  0.001595  0.002924   
33088  0.535803  0.004328  0.262226  0.036356  0.003342  0.019496  0.071158   

             p8        p9  pshooter  
0      0.135529  0.015304  0.060217  
1      0.039363  0.037045  0.057835  
2      0.001068  0.033128  0.003288  
3      0.000016  0.000267  0.013980  
4      0.002151  0.000506  0.001480  
...         ...       ...       ...  
33084  0.014599  0.094403  0.009337  
33085  0.003683  0.000796  0.035828  
33086  0.298282  0.056491  0.071591  
33087  0.002080  0.048923  0.000034  
33088  0.011235  0.050702  0.005354  

[33089 rows x 10 columns]

In [532]:
game_info = score_data[["GAME_ID", "GAME_EVENT_ID"]].drop_duplicates()

In [533]:
game_info

GAME_ID  GAME_EVENT_ID
0        21500001              8
100      21500001             20
200      21500001             28
300      21500001             30
400      21500001             56
...           ...            ...
3308400  21500663            476
3308500  21500663            494
3308600  21500663            496
3308700  21500663            499
3308800  21500663            522

[33089 rows x 2 columns]

In [534]:
model_preds["GAME_ID"] = np.array(game_info["GAME_ID"])
model_preds["GAME_EVENT_ID"] = np.array(game_info["GAME_EVENT_ID"])

In [535]:
model_preds = model_preds[["GAME_ID", "GAME_EVENT_ID"] + column_names]

In [536]:
model_preds

GAME_ID  GAME_EVENT_ID        p1        p2        p3        p4  \
0      21500001              8  0.109615  0.012890  0.404860  0.235031   
1      21500001             20  0.154865  0.144697  0.099772  0.461496   
2      21500001             28  0.007708  0.740597  0.177601  0.008221   
3      21500001             30  0.078775  0.339698  0.440581  0.000027   
4      21500001             56  0.320549  0.372308  0.178323  0.086942   
...         ...            ...       ...       ...       ...       ...   
33084  21500663            476  0.358843  0.005388  0.044533  0.019903   
33085  21500663            494  0.000010  0.316702  0.001114  0.011671   
33086  21500663            496  0.000494  0.000675  0.006073  0.012143   
33087  21500663            499  0.000417  0.015195  0.919939  0.008853   
33088  21500663            522  0.535803  0.004328  0.262226  0.036356   

             p5        p6        p7        p8        p9  pshooter  
0      0.008143  0.006083  0.012329  0.135529  0.015304  0.060217  
1      0.001924  0.002698  0.000304  0.039363  0.037045  0.057835  
2      0.000664  0.000197  0.027528  0.001068  0.033128  0.003288  
3      0.126452  0.000088  0.000115  0.000016  0.000267  0.013980  
4      0.037137  0.000599  0.000005  0.002151  0.000506  0.001480  
...         ...       ...       ...       ...       ...       ...  
33084  0.048663  0.356423  0.047905  0.014599  0.094403  0.009337  
33085  0.331621  0.000642  0.297932  0.003683  0.000796  0.035828  
33086  0.548592  0.005575  0.000085  0.298282  0.056491  0.071591  
33087  0.000040  0.001595  0.002924  0.002080  0.048923  0.000034  
33088  0.003342  0.019496  0.071158  0.011235  0.050702  0.005354  

[33089 rows x 12 columns]

In [537]:
check = np.array(model_preds[["p1", "p2", "p3", "p4", "p5"]])
check2 = np.sum(check, axis = 1)

In [538]:
np.mean(check2)

0.77650386

In [539]:
np.mean(np.sum(y_train2[:, 0:5], axis = 1))

0.8101522404795791

In [501]:
model_preds.to_csv("~/Desktop/Deep_Learning/nba-movement-data/rebounding_data/data_sets/landing_isotropic_preds4.csv", index = False)

In [305]:
np.array(tf.keras.backend.eval([1,2,3]))

array([1, 2, 3])